name: "友链申请"
title: "feat(friends): 加入"
description: "为 Ad_closeNN 的 Blog 申请友链"
labels: "新友链,等待处理"
assignees: Ad-closeNN
body:
- type: checkboxes
  id: "yml-1"
  attributes:
    label: "检查项"
    description: "请逐个检查下列项目，并勾选确认"
    options:
    - label: "我已添加 [Ad_closeNN 的 Blog](https://blog.adclosenn.top) 的友链。"
      required: true
    - label: "我确认我的网站非 **采集站**、**论坛类站点** 等非 **个人博客** 类型的站点。"
      required: true
    - label: "我确认申请的站点目前可以在 **中国大陆境内使用中国电信、中国移动、中国联通、中国广电网络** 正常访问。"
      required: true
    - label: "我确认申请的友链是独立域名，可以使用如 `*.dpdns.org` 类域名，但请不要使用 `github.io`、`vercel.app` 类第三方 SaaS 自带的域名。"
      required: true
    - label: "我同意友链按钮按照友链申请时间进行排序，而**非**按A-Z排序。"
      required: true
    - label: "我同意若申请时或日后有违反上述规定，[Ad_closeNN 的 Blog](https://blog.adclosenn.top) 有权**自行删除友链，并在源 Issue 通知 Author。**"
      required: true
  
- type: input
  id: "yml-2"
  attributes:
    label: "站点名称"
    description: "网站所使用的标题，将显示在单个友链内顶部头像旁。请勿输入过长的名称，否则可能会被删除部分内容。"
  validations:
    required: true
- type: input
  id: "yml-3"
  attributes:
    label: "站点描述"
    description: "简单描述你的网站是什么，将显示在单个友链内最底部标题下方。一般 5-15 个字符即可。"
  validations:
    required: true
- type: input
  id: "yml-4"
  attributes:
    label: "站点 URL"
    description: "填写你的网站的 URL。"
  validations:
    required: true
- type: input
  id: "yml-5"
  attributes:
    label: "站点图片"
    description: "填写你的网站的 `favicon.ico` 或者你认为合适的、鲜明的、有辨识性的图片的 URL。注意不要使用不稳定的、常更换的链接。**请勿提供 NSFW 图片，否则将直接拒绝申请！**"
  validations:
    required: true
- type: textarea
  id: "yml-6"
  attributes:
    label: "其他"
    placeholder: "其他想说的可以在这里说。"
  validations:
    required: false
